export const ADD_TO_CART = 'ADD_TO_CART'
export const HANDLE_ADD = 'HANDLE_ADD'
export const HANDLE_SUBTRACT = 'HANDLE_SUBTRACT'

export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
